apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siva-pvc07
  namespace: ns07
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: fast-07
